[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "docx>=0.2.4",
    "pdf2image>=1.17.0",
    "pytesseract>=0.3.13",
    "streamlit>=1.50.0",
]
